---
- name: Prepare nodes
  hosts: all
  become: true
  roles:
    - common
    - containerd

- name: Bootstrap control plane
  hosts: k8s_control_plane
  become: true
  roles:
    - control-plane

- name: Join workers
  hosts: k8s_workers
  become: true
  roles:
    - worker-nodes

- name: Install CNI & MetalLB
  hosts: k8s_control_plane
  become: false
  gather_facts: false
  roles:
    - cni

- name: Post-install apps (optional)
  hosts: k8s_control_plane
  become: false
  gather_facts: false
  roles:
    - applications
