---
- name: Check if cluster is already initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: cluster_initialized

- name: Initialize Kubernetes cluster
  command: >
    kubeadm init
    --pod-network-cidr={{ pod_network_cidr }}
    --service-cidr={{ service_network_cidr }}
    --apiserver-advertise-address={{ ansible_default_ipv4.address }}
    --control-plane-endpoint={{ control_plane_endpoint }}
    --upload-certs
  when: not cluster_initialized.stat.exists
  register: kubeadm_init_output

- name: Create .kube directory for dev user
  file:
    path: /home/dev/.kube
    state: directory
    owner: dev
    group: dev
    mode: '0755'

- name: Copy admin.conf to dev user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/dev/.kube/config
    owner: dev
    group: dev
    mode: '0644'
    remote_src: yes

- name: Get join command for worker nodes
  shell: kubeadm token create --print-join-command
  register: join_command
  when: not cluster_initialized.stat.exists

- name: Save join command to file
  local_action:
    module: copy
    content: "{{ join_command.stdout }}"
    dest: "./join_command.txt"
  when: join_command.stdout is defined
